### ISSUE TITLE
[Nightly] No cookies visible in list, "Remove at Startup" checkbox missing

### ISSUE THREAD

**Issue by yekyau** [simomat/lowcarb#4]
Hello, thanks for creating a webextension alternative to Self-Destructing Cookies!

I've had it installed for a few days and have been letting it run passively, but upon visiting the config page today the selection box has been whited-out: https://i.imgur.com/CZl6KNk.png

This happens whether I click through using the toolbar icon or the about:addons page. Clicking refresh produces this browser console message:
```
result.dateAdded is undefined  ext-bookmarks.js:64
	convert chrome://browser/content/ext-bookmarks.js:64:5
	from self-hosted:621:17
	getAll chrome://extensions/content/ext-cookies.js:293:24
	bound getAll self-hosted:946:17
	call resource://gre/modules/ExtensionParent.jsm:612:24
	next self-hosted:1150:9
Error: An unexpected error occurred
```
Firefox Nightly 55.0a1 (build 20170510123730) on Linux

**Comment by simomat** [comment]
Thanks! Looks like something went wrong when the `getAll()` api was called and the error was not handled.
I'll add some error handling there and leaf a hint if really no cookies are there.

I wonder if an alerting mechanism would be useful to show that something went wrong.

**Comment by simomat** [comment]
In version 1.1.0, using the cookie API calls is covered by some error handling now and an "empty" placeholder is shown if there are really no entries.
However, the layout still looks quirky on nightly. I assume the rendering is just not stable on that branch.

**Comment by simomat** [comment]
With 1.1.9 the style errors are gone.
