### ISSUE TITLE
FF54 Cookie list emty

### ISSUE THREAD

**Issue by BooSN** [simomat/lowcarb#5]
Firefox 54 (RC) does show empty cookie list.

**Comment by simomat** [comment]
Hi, I cannot reproduce it. I just tested again with actual FF54 and a fresh profile. I installed lowcarb and it shows cookies.

Are you using a special setup?

**Comment by BooSN** [comment]
Can be closed. Aria2-WebUI created some nameless cookie. After deleting it lowcarb´s list came back.
Sorry for bothering.

ps. let me know if you want my cookies.sqlite (with broken cookie) for review.
