### ISSUE TITLE
List "Select which cookies to keep"

### ISSUE THREAD

**Issue by lin0lin0** [simomat/lowcarb#7]
older release had a clear distinction of selected URLs/IPs. It used to be blue marked. Not sure if it was older FF release or older lowcarb Release. But for a while the URLs/IPs are just a tiny change in font if selected or not, and I can not recognize if it is a new cookie which I am marking to keep, or un-selecting a before marked to keep cookie. (Also search engine did not help, due to the name - I just get diet advice)

**Comment by simomat** [comment]
Thanks for your feedback. Yes, I switched styling to Firefox default styles and I tried to stick to their colors to prevent theming could make it unreadable. But as you pointed out that made selected lines hart to recognize. Think I will change it soon.... and bring lowcarb back to addons.mozilla.org - it is available right now.
