### ISSUE TITLE
Feature request: sort by checked status or divide into sections.

### ISSUE THREAD

**Issue by 1920x1200** [simomat/lowcarb#9]
Hello, I have a feature request, hopefully it's ok to post it here. 

I'll start off by saying I love this extension and have been using it for a long time. I've tried other cookie managers but I always found them to be too complicated to set up. This one is very easy to use!

Over the years I have built up a long list of "safe" cookies that I'd like to keep. Periodically I go into the list to review and any new cookies and decide if I should keep them or not. Scrolling through the list with the only difference being the check mark is very tedious since everything is mixed together. It would be great if I could sort the list by checked status (All the checked items together and all the unchecked items together) or perhaps split the list into two sections. This would make discovering new items way easier. 

If this feature would be easy to add I would greatly appreciate if you considered adding it. Thank you!

**Comment by simomat** [comment]
Right spot to report, good description. I will add this.

**Comment by simomat** [comment]
Implemented in 3.1.0 which was just released. Feedback welcome.

**Comment by 1920x1200** [comment]
Wow the sort by checked is super helpful! Thank you!!!
